import { PDFDocument, rgb, StandardFonts, PDFPage, PDFFont } from 'pdf-lib';
import type { BaZiResult, BirthInfo } from './types';

const COLORS = {
  primary: rgb(0.2, 0.3, 0.6),
  secondary: rgb(0.6, 0.2, 0.2),
  accent: rgb(0.9, 0.6, 0.1),
  text: rgb(0.15, 0.15, 0.15),
  lightText: rgb(0.4, 0.4, 0.4),
  bg: rgb(0.97, 0.97, 0.98),
  border: rgb(0.85, 0.85, 0.88),
  white: rgb(1, 1, 1),
  elementWood: rgb(0.3, 0.69, 0.31),
  elementFire: rgb(0.96, 0.26, 0.21),
  elementEarth: rgb(1, 0.6, 0),
  elementMetal: rgb(0.62, 0.62, 0.62),
  elementWater: rgb(0.13, 0.59, 0.95),
};

const ELEMENT_COLORS_MAP: Record<string, any> = {
  'Wood': COLORS.elementWood,
  'Fire': COLORS.elementFire,
  'Earth': COLORS.elementEarth,
  'Metal': COLORS.elementMetal,
  'Water': COLORS.elementWater,
};

function wrapLines(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const test = current ? current + ' ' + word : word;
    if (font.widthOfTextAtSize(test, fontSize) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function drawTextBlock(
  page: PDFPage,
  text: string,
  x: number, y: number,
  font: PDFFont, fontSize: number,
  color: any, maxWidth: number, lineHeight: number,
) {
  const lines = wrapLines(text, font, fontSize, maxWidth);
  lines.forEach((line, i) => {
    page.drawText(line, { x, y: y - i * lineHeight, size: fontSize, font, color });
  });
  return y - lines.length * lineHeight;
}

async function drawPillarBox(
  page: PDFPage,
  x: number, y: number, w: number, h: number,
  label: string, stem: string, branch: string, element: string,
  font: PDFFont, boldFont: PDFFont, smallFont: PDFFont,
) {
  page.drawRectangle({ x, y, width: w, height: h, color: COLORS.white, borderColor: COLORS.border, borderWidth: 1 });
  page.drawText(label, { x: x + 8, y: y + h - 18, size: 9, font: boldFont, color: COLORS.lightText });
  page.drawText(stem.split(' (')[0], { x: x + 8, y: y + h - 42, size: 14, font: boldFont, color: COLORS.primary });
  page.drawText(branch.split(' (')[0], { x: x + 8, y: y + h - 62, size: 14, font: boldFont, color: COLORS.secondary });
  const elColor = ELEMENT_COLORS_MAP[element] || COLORS.accent;
  page.drawRectangle({ x: x + w - 30, y, width: 30, height: 10, color: elColor });
  page.drawText(element, { x: x + w - 28, y: y + 1, size: 7, font: smallFont, color: COLORS.white });
}

export async function generateBaZiReport(result: BaZiResult, birthInfo: BirthInfo): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const smallFont = await doc.embedFont(StandardFonts.Helvetica);
  const italicFont = await doc.embedFont(StandardFonts.HelveticaOblique);

  const PW = 612, PH = 792;
  const margin = 50;
  const contentW = PW - 2 * margin;

  // ========== PAGE 1: COVER ==========
  let page = doc.addPage([PW, PH]);
  page.drawRectangle({ x: 0, y: 0, width: PW, height: PH, color: COLORS.bg });
  page.drawRectangle({ x: 0, y: PH - 200, width: PW, height: 200, color: COLORS.primary });

  page.drawText('YOUR BAZI', { x: 50, y: PH - 100, size: 42, font: boldFont, color: COLORS.white });
  page.drawText('DESTINY REPORT', { x: 50, y: PH - 145, size: 36, font: boldFont, color: COLORS.accent });
  page.drawText('Ancient Chinese Four Pillars of Destiny', { x: 50, y: PH - 180, size: 14, font, color: COLORS.white });

  const infoY = PH - 280;
  page.drawText('Birth Information', { x: 50, y: infoY, size: 14, font: boldFont, color: COLORS.text });
  const dateStr = `${birthInfo.year}-${String(birthInfo.month).padStart(2, '0')}-${String(birthInfo.day).padStart(2, '0')}`;
  page.drawText(`Date: ${dateStr}`, { x: 50, y: infoY - 24, size: 11, font, color: COLORS.text });
  page.drawText(`Time: ${String(birthInfo.hour).padStart(2, '0')}:${String(birthInfo.minute).padStart(2, '0')}`, { x: 50, y: infoY - 44, size: 11, font, color: COLORS.text });
  page.drawText(`Location: ${birthInfo.city}, ${birthInfo.country}`, { x: 50, y: infoY - 64, size: 11, font, color: COLORS.text });
  page.drawText('Generated by AI · Powered by Ancient Chinese Wisdom', { x: 50, y: 40, size: 9, font: italicFont, color: COLORS.lightText });

  // ========== PAGE 2: FOUR PILLARS & ELEMENTS ==========
  page = doc.addPage([PW, PH]);
  page.drawRectangle({ x: 0, y: 0, width: PW, height: PH, color: COLORS.bg });
  page.drawText('YOUR FOUR PILLARS', { x: 50, y: PH - 50, size: 22, font: boldFont, color: COLORS.primary });
  page.drawText('Each pillar represents an aspect of your life journey:', { x: 50, y: PH - 78, size: 10, font, color: COLORS.lightText });

  const pillars = [
    { label: 'Year Pillar', ...result.yearPillar },
    { label: 'Month Pillar', ...result.monthPillar },
    { label: 'Day Pillar', ...result.dayPillar },
    { label: 'Hour Pillar', ...result.hourPillar },
  ];
  const boxW = 115, boxH = 85, gap = 15;
  pillars.forEach((p, i) => {
    const x = 50 + i * (boxW + gap);
    drawPillarBox(page, x, PH - 180, boxW, boxH, p.label, p.stem, p.branch, p.stemElement, font, boldFont, smallFont);
  });

  // Day Master highlight
  const dmY = PH - 230;
  page.drawRectangle({ x: 45, y: dmY - 30, width: PW - 90, height: 50, color: COLORS.accent, opacity: 0.1 });
  page.drawText(`YOUR DAY MASTER: ${result.dayMaster}`, { x: 60, y: dmY - 8, size: 16, font: boldFont, color: COLORS.primary });
  page.drawText(`Element: ${result.dayMasterElement} · Polarity: ${result.dayMasterYinYang}`, { x: 60, y: dmY - 28, size: 11, font, color: COLORS.text });

  // Element bars
  const elTitleY = dmY - 85;
  page.drawText('ELEMENT PROFILE', { x: 50, y: elTitleY, size: 16, font: boldFont, color: COLORS.primary });

  const elements = [
    { name: 'Wood', score: result.elements.wood },
    { name: 'Fire', score: result.elements.fire },
    { name: 'Earth', score: result.elements.earth },
    { name: 'Metal', score: result.elements.metal },
    { name: 'Water', score: result.elements.water },
  ];
  const maxScore = Math.max(...elements.map(e => e.score), 1);
  const barMaxW = 350;
  const barStartY = elTitleY - 55;

  // Element descriptions
  const elDesc: Record<string, string> = {
    'Wood': 'Growth, creativity, expansion',
    'Fire': 'Passion, warmth, transformation',
    'Earth': 'Stability, nourishment, grounding',
    'Metal': 'Structure, precision, discipline',
    'Water': 'Wisdom, flow, adaptability',
  };

  elements.forEach((el, i) => {
    const barY = barStartY - i * 38;
    page.drawText(el.name, { x: 50, y: barY + 4, size: 10, font: boldFont, color: COLORS.text });
    page.drawText(elDesc[el.name] || '', { x: 50, y: barY - 12, size: 7, font: italicFont, color: COLORS.lightText });
    page.drawRectangle({ x: 130, y: barY - 2, width: barMaxW, height: 14, color: COLORS.bg, borderColor: COLORS.border, borderWidth: 1 });
    const fillW = (el.score / maxScore) * barMaxW;
    const elColor = ELEMENT_COLORS_MAP[el.name] || COLORS.accent;
    if (fillW > 0) page.drawRectangle({ x: 130, y: barY - 2, width: Math.max(fillW, 2), height: 14, color: elColor });
    page.drawText(el.score.toFixed(1), { x: 130 + barMaxW + 8, y: barY + 1, size: 10, font, color: COLORS.text });
  });

  const luckyY = barStartY - elements.length * 38 - 15;
  page.drawText(`Lucky Element: ${result.luckyElement}`, { x: 50, y: luckyY, size: 12, font: boldFont, color: ELEMENT_COLORS_MAP[result.luckyElement] || COLORS.text });
  page.drawText(`Balancing Element: ${result.unfavorableElement}`, { x: 50, y: luckyY - 22, size: 12, font, color: COLORS.lightText });

  // ========== PAGE 3: PERSONALITY & INSIGHTS ==========
  page = doc.addPage([PW, PH]);
  page.drawRectangle({ x: 0, y: 0, width: PW, height: PH, color: COLORS.bg });
  page.drawText('PERSONALITY PROFILE', { x: 50, y: PH - 50, size: 22, font: boldFont, color: COLORS.primary });

  let ny = PH - 85;
  result.personalityTraits.forEach((trait) => {
    page.drawCircle({ x: 62, y: ny + 3, size: 3, color: COLORS.accent });
    page.drawText(trait, { x: 76, y: ny, size: 10, font, color: COLORS.text });
    ny -= 22;
  });

  ny -= 15;
  page.drawText('CAREER INSIGHT', { x: 50, y: ny, size: 16, font: boldFont, color: COLORS.primary });
  ny = drawTextBlock(page, result.careerInsight, 50, ny - 22, font, 10, COLORS.text, contentW, 16) - 15;

  page.drawText('RELATIONSHIP INSIGHT', { x: 50, y: ny, size: 16, font: boldFont, color: COLORS.primary });
  ny = drawTextBlock(page, result.relationshipInsight, 50, ny - 22, font, 10, COLORS.text, contentW, 16) - 15;

  page.drawText('WEALTH INSIGHT', { x: 50, y: ny, size: 16, font: boldFont, color: COLORS.primary });
  ny = drawTextBlock(page, result.wealthInsight, 50, ny - 22, font, 10, COLORS.text, contentW, 16);

  // ========== PAGE 4: HIDDEN STEMS TABLE ==========
  page = doc.addPage([PW, PH]);
  page.drawRectangle({ x: 0, y: 0, width: PW, height: PH, color: COLORS.bg });
  page.drawText('HIDDEN STEMS & TEN GODS', { x: 50, y: PH - 50, size: 22, font: boldFont, color: COLORS.primary });
  page.drawText('Each Earthly Branch contains hidden Heavenly Stems that reveal deeper layers of your destiny.', { x: 50, y: PH - 78, size: 10, font, color: COLORS.lightText });

  // Table
  const tableData = [
    { pillar: 'Year', ...result.yearPillar },
    { pillar: 'Month', ...result.monthPillar },
    { pillar: 'Day', ...result.dayPillar },
    { pillar: 'Hour', ...result.hourPillar },
  ];

  const cols = [{ x: 50, w: 60 }, { x: 110, w: 90 }, { x: 200, w: 100 }, { x: 310, w: 130 }, { x: 440, w: 110 }];
  const headers = ['Pillar', 'Animal', 'Hidden Stems', 'Ten God (Stem)', 'Ten God (Branch)'];
  const tableY = PH - 120;

  page.drawRectangle({ x: 45, y: tableY - 5, width: 520, height: 22, color: COLORS.primary });
  headers.forEach((h, i) => {
    page.drawText(h, { x: cols[i].x, y: tableY + 1, size: 8, font: boldFont, color: COLORS.white });
  });

  tableData.forEach((row, ri) => {
    const ry = tableY - 30 - ri * 24;
    if (ri % 2 === 0) page.drawRectangle({ x: 45, y: ry - 5, width: 520, height: 24, color: rgb(0.95, 0.95, 0.98) });
    const animal = row.branch.match(/\((.+)\)/)?.[1] || row.branch;
    page.drawText(row.pillar, { x: cols[0].x, y: ry + 1, size: 9, font: boldFont, color: COLORS.text });
    page.drawText(animal, { x: cols[1].x, y: ry + 1, size: 9, font, color: COLORS.text });
    page.drawText(row.hiddenStems.join(', '), { x: cols[2].x, y: ry + 1, size: 8, font, color: COLORS.text });
    page.drawText(row.shiShen, { x: cols[3].x, y: ry + 1, size: 8, font, color: COLORS.text });
    const branchTG = row.hiddenStems.slice(0, 2).join(', ');
    page.drawText(branchTG, { x: cols[4].x, y: ry + 1, size: 7, font, color: COLORS.text });
  });

  // ========== PAGE 5: SUMMARY ==========
  page = doc.addPage([PW, PH]);
  page.drawRectangle({ x: 0, y: 0, width: PW, height: PH, color: COLORS.bg });
  page.drawText('YOUR DESTINY SUMMARY', { x: 50, y: PH - 60, size: 22, font: boldFont, color: COLORS.primary });

  // Summary box
  const boxTop = PH - 90;
  const sumBoxH = 120;
  page.drawRectangle({ x: 45, y: boxTop - sumBoxH, width: PW - 90, height: sumBoxH, color: COLORS.white, borderColor: COLORS.border, borderWidth: 1 });
  drawTextBlock(page, result.summary, 60, boxTop - 18, font, 10, COLORS.text, PW - 120, 15);

  const recY = boxTop - sumBoxH - 30;
  page.drawText('ELEMENT RECOMMENDATIONS', { x: 50, y: recY, size: 16, font: boldFont, color: COLORS.primary });

  const elementTips: Record<string, string[]> = {
    'Wood': ['Wear green and brown colors', 'Spend time in forests or gardens', 'Start new projects in spring', 'Stretch and practice yoga'],
    'Fire': ['Use red and purple accents', 'Engage in physical activity', 'Socialize and network often', 'Express yourself creatively'],
    'Earth': ['Wear yellow and orange tones', 'Focus on stability and routine', 'Eat root vegetables', 'Practice mindfulness daily'],
    'Metal': ['Use white and gold decor', 'Declutter your living space', 'Study and organize regularly', 'Set clear boundaries'],
    'Water': ['Wear blue and black shades', 'Spend time near water', 'Meditate and reflect daily', 'Flow with life changes'],
  };

  const tips = elementTips[result.luckyElement] || elementTips['Earth'];
  tips.forEach((tip, i) => {
    page.drawCircle({ x: 62, y: recY - 30 - i * 22, size: 2.5, color: ELEMENT_COLORS_MAP[result.luckyElement] || COLORS.accent });
    page.drawText(tip, { x: 76, y: recY - 35 - i * 22, size: 9, font, color: COLORS.text });
  });

  // Lucky info section
  const luckyY2 = recY - 30 - tips.length * 22 - 30;
  page.drawText('LUCKY DIRECTIONS & CRYSTALS', { x: 50, y: luckyY2, size: 14, font: boldFont, color: COLORS.primary });

  const directionMap: Record<string, string> = {
    'Wood': 'East · SouthEast',
    'Fire': 'South',
    'Earth': 'Center · SouthWest · NorthEast',
    'Metal': 'West · NorthWest',
    'Water': 'North',
  };
  const crystalMap: Record<string, string> = {
    'Wood': 'Green Jade, Emerald, Moss Agate',
    'Fire': 'Ruby, Carnelian, Red Agate',
    'Earth': 'Citrine, Tiger Eye, Yellow Jasper',
    'Metal': 'Clear Quartz, Selenite, White Howlite',
    'Water': 'Lapis Lazuli, Black Obsidian, Aquamarine',
  };

  page.drawText(`Lucky Direction: ${directionMap[result.luckyElement] || '—'}`, { x: 50, y: luckyY2 - 22, size: 10, font, color: COLORS.text });
  page.drawText(`Recommended Crystals: ${crystalMap[result.luckyElement] || '—'}`, { x: 50, y: luckyY2 - 40, size: 10, font, color: COLORS.text });
  page.drawText(`Career Direction: Industries aligned with ${result.luckyElement} energy`, { x: 50, y: luckyY2 - 58, size: 10, font, color: COLORS.text });

  page.drawText('This report is for entertainment and self-reflection purposes only.', { x: 50, y: 30, size: 8, font: italicFont, color: COLORS.lightText });

  return doc.save();
}
